### ISSUE TITLE
Can't run pipeline, multiple issues

### ISSUE THREAD

**Issue by fbleao** [sims-lab/CapCruncher#266]
Dear, 

I'm trying to run capcruncher pipeline without success so far, running into multiple issues. I'm not a bioinformatician, so any help would be greatly appreciated. 

First, I can't adjust the config file by the suggested command `capcruncher pipeline-config` as it outputs "Error: No such command 'pipeline-config'." Is this function still available?

I then manually modified the capcruncher_config_example.yml, which I believe should work. 

Trying `capcruncher pipeline --cores 8`outputs "Error: Invalid value for '{make|plot|show|clone|touch}': '--cores' is not one of 'make', 'plot', 'show', 'clone', 'touch'."

Finally, trying `capcruncher pipeline make` outputs:

"CapCruncher CLI:113: UserWarning: DRMAA_LIBRARY_PATH is incorrect. Implicitly using --local with 4 cores
Traceback (most recent call last):
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/capcruncher/pipeline/pipeline.py", line 45, in <module>
    from cgatcore import pipeline as P
ModuleNotFoundError: No module named 'cgatcore'
Traceback (most recent call last):
  File "/Users/felipe/miniforge3/bin/capcruncher", line 10, in <module>
    sys.exit(cli())
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/felipe/miniforge3/lib/python3.10/site-packages/capcruncher/cli/__init__.py", line 99, in pipeline
    raise RuntimeError("CapCruncher pipeline failed. Check pipeline.log for details")
RuntimeError: CapCruncher pipeline failed. Check pipeline.log for details"

Any suggestions? 

Thank you very much

**Comment by alsmith151** [comment]
Hi,

It appears like an older version of the capcruncher package has been installed.  In the appropriate conda environment try running:

```bash
pip install "capcruncher[full]==0.3.11" 
```

This should ensure that you have the latest version, that will correspond with the documentation.
